DROP TABLE IF EXISTS "colleges" CASCADE;
DROP TABLE IF EXISTS "companies" CASCADE;
DROP TABLE IF EXISTS "branches" CASCADE;
CREATE TABLE IF NOT EXISTS "colleges" ("id"   SERIAL , "name" VARCHAR(255) NOT NULL UNIQUE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, UNIQUE ("name"), PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "branches" ("id"   SERIAL , "code" VARCHAR(6) UNIQUE, "name" VARCHAR(255) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, UNIQUE ("code"), PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "companies" ("id"   SERIAL , "name" VARCHAR(255) NOT NULL UNIQUE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, UNIQUE ("name"), PRIMARY KEY ("id"));
